/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export interface IVersion {
    id?: string;
    indice: number;
    visas: readonly {
        authorId: string;
        statusId: string;
        comment?: string;
    }[];
    topVisa?: {
        authorId: string;
        statusId: string;
        comment?: string;
    };
}
